FEAT: adicionando debug de credenciais

diff --git a/.github/workflows/aws-deploy.yml b/.github/workflows/aws-deploy.yml
--- a/.github/workflows/aws-deploy.yml
+++ b/.github/workflows/aws-deploy.yml
@@ -81,18 +81,25 @@ jobs:
           # SSH into EC2 and run deployment commands
           # We pass the AWS credentials from the runner to the EC2 session
           ssh -i ~/.ssh/id_rsa "$EC2_USER@$EC2_HOST" "
-            export AWS_ACCESS_KEY_ID='${{ env.AWS_ACCESS_KEY_ID }}'
-            export AWS_SECRET_ACCESS_KEY='${{ env.AWS_SECRET_ACCESS_KEY }}'
-            export AWS_SESSION_TOKEN='${{ env.AWS_SESSION_TOKEN }}'
+            export AWS_ACCESS_KEY_ID='${AWS_ACCESS_KEY_ID}'
+            export AWS_SECRET_ACCESS_KEY='${AWS_SECRET_ACCESS_KEY}'
+            export AWS_SESSION_TOKEN='${AWS_SESSION_TOKEN}'
             set -e # Exit script on any error
 
             echo 'Checking AWS CLI installation...'
-            if ! command -v aws &> /dev/null; then
-                echo 'Installing AWS CLI...'
-                curl \"https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip\" -o \"awscliv2.zip\"
-                unzip awscliv2.zip
-                sudo ./aws/install
-                rm -rf aws awscliv2.zip
+            aws --version
+
+            echo 'Debugging AWS credentials...'
+            echo \"AWS_ACCESS_KEY_ID length: \${#AWS_ACCESS_KEY_ID}\"
+            echo \"AWS_SECRET_ACCESS_KEY length: \${#AWS_SECRET_ACCESS_KEY}\"
+            echo \"AWS_SESSION_TOKEN length: \${#AWS_SESSION_TOKEN}\"
+
+            echo 'Testing AWS credentials...'
+            if aws sts get-caller-identity; then
+                echo 'AWS credentials are valid'
+            else
+                echo 'AWS credentials test failed'
+                exit 1
             fi
 
             echo 'Logging into AWS ECR...'
